Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -67,9 +67,9 @@ steps:
       
       reportfortify=$(java -jar /opt/fortify-api-client/fortify-api-client-latest.jar legacyReport -n $(Build.Repository.Name) -v $(Build.SourceBranchName) | grep -v "sun.reflect.Reflection.getCallerClass") echo -e "\033[33m \n ${reportfortify}  \n \033[0m" 
   
-        # if expr ${reportfortify//[[:space:]]/} : ".*0Criticas(Novas)*."; then
-        #   echo "##vso[task.logissue type=success;] Analise Fortify SAST concluída com sucesso!"
-        # else
-        #   echo "##vso[task.logissue type=error;] Error na Analise SAST encontrado problemas críticos de seguranca na análise Fortify /n Projeto:$(Build.Repository.Name) /n Branch:$(Build.SourceBranchName)"
-        #   exit 1
-        fi
+        # # if expr ${reportfortify//[[:space:]]/} : ".*0Criticas(Novas)*."; then
+        # #   echo "##vso[task.logissue type=success;] Analise Fortify SAST concluída com sucesso!"
+        # # else
+        # #   echo "##vso[task.logissue type=error;] Error na Analise SAST encontrado problemas críticos de seguranca na análise Fortify /n Projeto:$(Build.Repository.Name) /n Branch:$(Build.SourceBranchName)"
+        # #   exit 1
+        # fi
